### ISSUE TITLE
Does Mixpanel-swift support the ipv6?

### ISSUE THREAD

**Issue by uc3po** [mixpanel/mixpanel-swift#118]
Hi,
My iOS app was rejected, "Itunesconnect- Resolution Center" message is: Your app crashed on iPad running iOS 10.3.3 connected to an IPv6 network when we tapped on the button...
I'm using MixPanel. I trigger an MixPanel event on button clicked so i assume that the MixPanel swift lib does not support ipv6. 

I checked Mixpanel and  MixPanel's app link
( https://mixpanel.com/report/[mymixpanelprojectid]/explore/  )
from http://ipv6-test.com/validate.php this site. And it says link is not available on ipv6.

Does Mixpanel support the ipv6 networking?
Thanks.

**Comment by yarneo** [comment]
Hi @uc3po,
As far as I remember, it has been a standard at Apple for years now to check IPv6 as well as different devices (iPad included) when doing an app store submission review.
We are not aware of any other submissions ever failing/crashing on IPv6 due to having the Mixpanel SDK in their app. Would you mind sharing a crash report showing this is Mixpanel related?
