### ISSUE TITLE
Shouldn't currentSuperProperties return Properties instead of [String : Any]

### ISSUE THREAD

**Issue by plerma** [mixpanel/mixpanel-swift#124]
Hi!

We are migrating from Mixpanel Objective-C SDK to Swift SDK. 
Why is `currentSuperProperties` returning `[String : Any]` instead of `Properties`?

We want to get the superProperties and add or override a new one and it's a bit misleading to have to cast the `[String : Any]` in a helper function (since if we don't do that we have a crash in our assertion).

I.e. snippet:
```
guard var properties = mixpanel.currentSuperProperties() as? Properties else {
	assertionFailure("Unable to cast Mixpanel SuperProperties to Properties")
	return
}
properties["ourPropertyKey"] = "stringValue"
mixpanel.registerSuperProperties(properties)
```

Thanks!

**Comment by yarneo** [comment]
Hey @plerma , thanks for writing in.

I definitely see the pain point with the casting and the intent. The reason we wanted it to return a [String: Any] is because the usual use case is to fetch the superProperties for app usage rather than sending it back to Mixpanel, and therefore we didn't want to force the user to use an internal Mixpanel property type "Properties" which has "MixpanelType". 

In terms of overriding a super property, if you call `registerSuperProperties` with a certain key value, it will override the existing value if that key already exists. Also there is no need to have all the key/values registered each time. For instance if I do `registerSuperProperties(["a": 1])` and then later `registerSuperProperties(["b": 2])` then both "a" and "b" will be part of the super properties.

**Comment by plerma** [comment]
Oh, we didn't realize that were getting the superproperties just to override them. We have remove that part so we don't need our helper function to cast the properties. Thanks!
