### ISSUE TITLE
Crash on Mixpanel.initialize(token: "MY_TOKEN")

### ISSUE THREAD

**Issue by normdoow** [mixpanel/mixpanel-swift#161]
Hello,

I am using mixpanel-swift: 2.2.2
using Swift 4
Currently testing on iOS 11

I am having a crash just after calling `Mixpanel.initialize(token: "MY_TOKEN")` inside of Appdelegate's didFinishLaunchingWithOptions function.

It appears that the crash is happening in the background and i am not able to catch it to see what the stack trace is. Here is where the debugger stops it when it crashes in the Mixpanel-swift/Complete/UIViewSelectors.swift file...

<img width="1118" alt="screen shot 2017-11-28 at 6 02 53 pm" src="https://user-images.githubusercontent.com/21371266/33349180-12a3f5c0-d467-11e7-8d86-dbeb5e771cbe.png">

Is there any way i can get a better error log so we can better know what this issue is? Is there anything that I am doing wrong?

Thanks!

**Comment by pchien** [comment]
Hi @normdoow. Are you using the `swift4` or `master` branch? Are you integrating through Cocoapods or Carthage or manually? It looks like the crash might be in a/b test or codeless tracking related code. Is your crash on the `Mixpanel.initialize` line? Do you know if you're using a/b testing or codeless tracking (probably not since you're just initializing for the first time)?

**Comment by normdoow** [comment]
Thanks for the reply @pchien. 
I am using swift4 and cocoapods. This is what is in my podfile...
`pod 'Mixpanel-swift', :git=> 'https://github.com/mixpanel/mixpanel-swift.git', :branch=> 'swift4'`

I am using codeless tracking but not a/b testing. I'm guessing codeless testing is when you trigger events from the web app interface correct? 

The crash is not on the Mixpanel.initialize line. It is in the background after calling initialize. One thing I forgot to mention is that on fresh install calling `Mixpanel.initialize` works fine and does not crash but the second time or anytime after that it will crash.

**Comment by pchien** [comment]
Ah I see. It looks like it's crashing because of codeless tracking. For now would it work for you to add `track` calls manually to your code? It should at least let you do some tracking until we figure out why it's crashing.

**Comment by normdoow** [comment]
Yeah, that is fine with me. Isn't there a couple of codeless tracking events that are automatic that I can't stop such as `app session` and `First App Open`? Or is there a way to turn codeless tracking off completely?

**Comment by pchien** [comment]
Those events shouldn't be going through this code path. If you set `enableVisualEditorForCodeless` to `false` it should stop you from editing codeless events. If that doesn't stop the crash, you might have to remove currently tracking codeless events. I wonder if it's caused by an event that's tracking on a view that you've changed since you set up tracking? I'm not sure exactly how that case works.

**Comment by normdoow** [comment]
I set enableVisualEditorForCodeless to false and that seemed to fix the crash.
