### ISSUE TITLE
MixPanel decreases UI performance of the app

### ISSUE THREAD

**Issue by tevghenii** [mixpanel/mixpanel-swift#172]
Hi guys,

We use Mixpanel in our app and discovered that Mixpanel has negative impact on UI performance of the app, e.g. screens are freezed for about 2 second after pushed in navigation controller and some other lags.
When I disabled the mixpanel the app become more responsive.

I examined the app time profiler and found that Mixpanel heavy loads the main thread, main thread is sometimes 100% busy with mixpanel enabled.

Any tips how to increase performance of the Mixpanel? We use it for analytics and push notifications, but this performance issue is very annoying.

I attached a screenshot from time profiler with usage statistics.

Thank you!

![screen shot 2018-01-09 at 15 07 41](https://user-images.githubusercontent.com/7658367/34722573-13c04706-f550-11e7-934d-75ad9f7193cd.png)

**Comment by pchien** [comment]
@tevghenii it looks like the code that's causing the performance impact is related to A/B testing. Unfortunately, because it has to interact with UIKit, it has to occur on the main thread. Are you running visual A/B tests on the view controllers that are slow? I believe this code shouldn't be running if you're not running A/B tests. It's a little odd that it looks like it's being called constantly though. I think, depending on the visual element changed, it either runs on `layoutSubviews` or `didMoveToWindow` so maybe there's something that's causing your view to call `layoutSubviews` every frame? Let me know if any of this helps.

**Comment by tevghenii** [comment]
@pchien Your are right, the reason of hit on performance was enabled A/B tests. When we disabled the issue disappeared.

**Comment by pchien** [comment]
Thanks @tevghenii! Feel free to reopen this if you have more issues.
