### ISSUE TITLE
`creatAlias` creating multiple Mixpanel profiles

### ISSUE THREAD

**Issue by MaroofKhan** [mixpanel/mixpanel-swift#178]
`createAlias` is creating 2 profiles on Mixpanel. One, with the original distinct ID, and other with the new aliased ID. Although the profile with the original distinct ID works perfectly (i.e events before/after aliasing, and events after identifying), it leaves an empty profile with the new aliased ID.

**Comment by cassiegamm** [comment]
Hi @MaroofKhan,

Are you sending profile data from a server after a user registers for an account? Or are all updates to user's profiles occurring through the Swift SDK?

If you're sending profile data from a server immediately after creating an alias, you can prevent duplicate profiles from being created by using the mixpanel.distinctId on the iphone as the distinct_id (rather than the alias) for any profile updates that occur when an alias is created. 

If you're only using the Swift SDK to send profile data, it would be helpful if you could share the createAlias and Identify calls that your app is executing as well as the SDK version. I'd be happy to help debug.

**Comment by MaroofKhan** [comment]
It figured it out. Thanks @cassiegamm!
