### ISSUE TITLE
Codeless / AutoTrack show black screen

### ISSUE THREAD

**Issue by marcalzup** [mixpanel/mixpanel-swift#215]
I configured everything correctly and it still displays only a black screen.
Does anyone know if this functionality works correctly for swift projects?

**Comment by cassiegamm** [comment]
Hi @marcalzup,

If you're seeing a black screen the Codeless event tracker is having trouble picking the activated view from your app. This generally happens [if you have a view that is the default in your app but is not at the top of the stack](https://help.mixpanel.com/hc/en-us/articles/115004615486-Black-Screen-When-Connecting-Device).

The problem can be fixed by stacking the views in your app differently. You should be able to identify which view is making its way to the top of your app using the Xcode debugger.

If you would like further assistance with this issue or more details on how to resolve this issue, please reach out to support@mixpanel.com.

**Comment by marcalzup** [comment]
Hi, Cassie.

Strange that when I enable autotrack on the device (using 4 fingers) it adds a new UIWindow in the structure and uses it. You have not gone wrong with my Views hierarchy. This is what is causing the black screen.

Can you help me?

**Comment by zihejia** [comment]
hi @marcalzup, sorry for the late response. 

The new UIWindow is added by Mixpanel but it should not cause the black window. Since it's not SDK related issue, closing this one out, please re-open if you're still experiencing any problem.
