### ISSUE TITLE
swift 4.2.1 build fails with carthage

### ISSUE THREAD

**Issue by abdullah-s** [mixpanel/mixpanel-swift#266]
Integration Method: Carthage
Xcode Version: 10.1
Library Version: 2.5.4
Platform: iOS
Language: Swift
Description:
library must be complied with Swift 4.2.1
i get the following error when i run "carthage update --platform iOS"
*** Downloading mixpanel-swift.framework binary at "v2.5.4 - Send device_id and user_id with event/people updates"
*** Skipped installing mixpanel-swift.framework binary due to the error:
"Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."
Expected Behavior:
command should not fail

**Comment by zihejia** [comment]
Hi @abdullah-s ,  thanks for raising it. we will release a new version with Swift 4.2.1.  One pain point of Carthage is that we have to ship the prebuilt framework using our local Swift version. Since v2.5.4 was released prior to Swift 4.2.1 release,  so it was built with Swift 4.2 only.

However, it should be able to fall back to fetch and build from the source code. If it didn't, please try with the command `Carthage update --no-use-binaries`.  That will force it to build from the source. Remember to delete Carthage folder and re run it. 

Please checkout https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility for more detail.

**Comment by zihejia** [comment]
hi @abdullah-s , please try again with v2.5.5. I've updated it with Swift 4.2.1. Please let me know if still any issue. Once again, thanks for bringing it up. Closing this one now.

**Comment by abdullah-s** [comment]
thank you @zihejia for the short notice response, your efforts are highly appreciated.
i'll update now
