### ISSUE TITLE
Migrating from Obj-C library to Swift resets distinctId

### ISSUE THREAD

**Issue by jarosan** [mixpanel/mixpanel-swift#274]
I've been trying to migrate from Obj-c version of Mixpanel SDK to Swift and noticed that old `distinctId`-s generated by obj-c version are not used and new ones are generated. Quick investigation showed that obj-c and swift libraries are storing it differently (although I've only spent 5 minutes looking so might be wrong here).

Does this mean that if we want to preserve distinct ids then we would never be able to migrate to swift? Maybe you could make a fix for this?

**Comment by zihejia** [comment]
hi @jarosan , sorry for the late response and you are correct.  Since obj-c and swift persist the cache(events not being flushed, distinctId, etc) differently, the cache won't be restored when you switch. Unfortunately, we currently don't have any plans to make the persisted cache compatible in between swift and objc. However, you can set your own distinctId and preserve it in app to make it consistent, hope this won't hold you back for switching to swift. 
https://help.mixpanel.com/hc/en-us/articles/115004496863-Distinct-ID-Discrepancy

If you have more questions about this, you are welcome to contact Mixpanel support for more detail.

**Comment by fabiendem** [comment]
@zihejia We're facing the issue described here, but the link to https://help.mixpanel.com/hc/en-us/articles/115004496863-Distinct-ID-Discrepancy is dead.
Do you have this documentation somewhere else?

Or have things changed since 2019 WRT the migration of a project from Obj-C to Swift?

Cheers!

**Comment by fabiendem** [comment]
Actually I think I have found it https://community.mixpanel.com/data-management-10/distinct-id-discrepancy-articles-from-the-archive-2726

But I am not sure to understand how this is helping us with the migration from Objc-C to Swift for our existing users already logged in.
