### ISSUE TITLE
A/B Developer tweaks won't update

### ISSUE THREAD

**Issue by vovastalnyi** [mixpanel/mixpanel-swift#302]
Hi I've encountered an issue recently. Once tweaks for A/B testing retrieves a value it won't ever update it until you turn an experiment off and on back again, making sure that app received inactive experiment.
After examining **Decide.swift** I found something in lines 133-135.
```
let newVariants = parsedVariants.subtracting(runningVariants)
decideResponse.newVariants = newVariants
self.ABTestingInstance.variants = newVariants.union(runningVariants)
```
Since Variant has an overridden hash function that only checks ID and refrain from checking contents of experiment, updated values of experiment would not be written to self.ABTestingInstance.variants therefore would not be archived and user would have same values even after restarting an app.

I propose to update it to something like this:
```
decideResponse.newVariants = parsedVariants.subtracting(runningVariants)
self.ABTestingInstance.variants = parsedVariants.union(runningVariants)
```
Here `decideResponse.newVariants` would get correct `newVariants` and `self.ABTestingInstance.variants` would get a proper copy of Variant and won't miss anything already running.

**Comment by vovastalnyi** [comment]
It's not related but I've also noticed that new variants won't be executed until an app got restarted. Is it expected?

**Comment by gkye** [comment]
Currently also experiencing the same issue, has there been an update on this?

**Comment by vovastalnyi** [comment]
@zihejia Can you take a look at this one, please?

**Comment by vovastalnyi** [comment]
❤️ Thank you!

**Comment by nikolayev** [comment]
Also facing same issue, would be super cool if that PR goes through, thanks!

**Comment by zihejia** [comment]
Thanks everyone for bringing this up, we have released a new version contains a fix for it. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.4. I'm closing this one now, please feel free to open it if the problem still exists.

**Comment by nikolayev** [comment]
I'm still facing the same issue. Thing is, #305 didn't really address the issue. What changed:
```
let newVariants = parsedVariants.subtracting(runningVariants)
decideResponse.newVariants = newVariants
self.ABTestingInstance.variants = newVariants.union(runningVariants)
```
Became 
```
decideResponse.newVariants = parsedVariants.subtracting(runningVariants)
self.ABTestingInstance.variants = parsedVariants.subtracting(runningVariants).union(runningVariants)
```
Issue still arise because `Set.union()` doesn't replace variant with old tweaks with the new tweaks variant. Replace doesn't happen because `Variant.isEqual` doesn't include tweaks into comparison, e.g:
```
Variant1: 
{ 
    "notifications":[ ],
    "variants":[ 
        { 
            "tweaks":[ 
                { 
                    "name":"Tweak name",
                    "encoding":"@",
                    "default":"",
                    "maximum":null,
                    "value":"value1",
                    "minimum":null,
                    "type":"string"
                }
            ],
            "actions":[ ], "id":205809, "experiment_id":93657
        }
    ], "automatic_events":false, "integrations":[ ]
}

Variant 2:
{ 
    "notifications":[ ],
    "variants":[ 
        { 
            "tweaks":[ 
                { 
                    "name":"Tweak name",
                    "encoding":"@",
                    "default":"",
                    "maximum":null,
                    "value":"value2",
                    "minimum":null,
                    "type":"string"
                }
            ],
            "actions":[ ], "id":205809, "experiment_id":93657
        }
    ], "automatic_events":false, "integrations":[ ]
}
```
Difference between those 2 Variants is that they have tweaks with same name but different values. Because `Variant.isEqual` includes only `ID` and `actions` comparison - **Variant1** will be considered as equal to **Variant2**. Going further - `VariantTweak.isEqual` doesn't compare values, so `VariantTweak(name: "Foo", value: 1)` will equal to `VariantTweak(name: "Foo", value: 2)`(sorry for pseudocode, don't want to make this comment larger than it is). 

Resetting experiment via Mixpanel website bumps `Variant.ID` so `isEqual` check begins to work and edited values are fetched successfully.

Question arises here: is it a **by-design** behavior that we can't change experiment values on-the-fly without resetting the experiment? If not - we need to do 2 things here:
1) Update `Variant.isEqual` to compare not only `ID` and `actions` but also `tweaks` property
2) Update `VariantTweak.isEqual` to compare not only `name` but also `value`
