### ISSUE TITLE
SuperProperties Bool value changing to Int after unarchive SuperProperties Bug

### ISSUE THREAD

**Issue by TheCodeTalker** [mixpanel/mixpanel-swift#342]
We are facing bug on SDK side where we are registering the super properties key ex- : "User Registration?" as Bool. But after killing and reopening the app When Mixpanel Unarchive the properties as to the data Type we have seen bool is converting as Int Ex- ```- key : "User Registration?"
    - value : 0```

**Comment by zihejia** [comment]
The solution for this issue is to use NSNumber instead. In swift, Bool type will always archive as 0 or 1. When unarchiving, unless you know it’s Bool and explicitly decode it to Bool, there is no additional info carried besides 0 or 1 as Int. However, NSNumber does carry bool/int type info and swift can use the bridge version of NSNumber from objc, as long as you store Bool value using NSNumber, it will just work when unarchive. 
Here is one example: 
```    
        let aBoolNumber: Bool = true
        let aBoolNSNumber = NSNumber(value: aBoolNumber)
        
        let aIntNumber: Int = 1
        let aIntNSNumber = NSNumber(value: aIntNumber)
       
        mixpanel.track(event: "e1", properties:  ["p1": aBoolNSNumber, "p2": aIntNSNumber])
```
When unarchive. you can use CFGetTypeID to check if it's Bool or not:
```
if CFGetTypeID(aNSNumber) == CFBooleanGetTypeID()
```

We've released a new version v2.7.2 https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.7.2, to support storing NSNumber value. which contains the fix. I'm closing this one, please feel free to reopen it if the problem still exists.
