### ISSUE TITLE
Mixpanel initialization causes memory crash

### ISSUE THREAD

**Issue by holykou** [mixpanel/mixpanel-swift#346]
An ipad application I'm developing is currently killed by iOS because of memory overuse. I spent hours trying to figure out where the memory is being used, and finally it turned out to be the line of code that initializes the Mixpanel swift library. This crash does not happen on all devices, but only on some devices that are all iPad Pros. I removed the mixpanel initialization and the memory usage stays within 30-50 MB, but with the initialization the memory goes upto 3.2GB(!) and then the app crashes. Any help to figure out how to avoid this will be great.

**Comment by zihejia** [comment]
hi @holykou have you tried our latest version v2.6.11?

**Comment by holykou** [comment]
@zihejia, yes. The issue persists even with the latest version of Mixpanel.

**Comment by zihejia** [comment]
It seems iOS 13 is a lot stricter and more aggressive killing apps. i'm suspecting those devices have accumulated large archived events, normally this happens when the devices have been offline for a while but consistently triggering events. Could that be case? If so, could you try a clean install on one of those device and see if it still happens? We might need to tweak the offline event queue size for archiving, now it's 5000.

**Comment by holykou** [comment]
@zihejia yes, we've tried multiple clean installs. Only way the app seems to work at this point is by removing the mixpanel init.

**Comment by holykou** [comment]
@zihejia we tried a clean install and the app no longer crashes. Apologies, we hadn't tried a clean install yet since we were trying to fix the problem while the app is in this state.

**Comment by zihejia** [comment]
Thanks @holykou , I'm closing this one now.

**Comment by zihejia** [comment]
v2.6.11 has a fix for this problem. Feel free to reopen it if the problem still exits in future.

**Comment by holykou** [comment]
The app crashed with v2.6.11 as well. Reopening this issue.
