### ISSUE TITLE
checking for mix-panel initialization 

### ISSUE THREAD

**Issue by AmrAbedal** [mixpanel/mixpanel-swift#401]
instead of crashing the app in case that mixpanel not initialized  , give us the ability to check if the main instance is already initialized .

**Comment by TimPapler** [comment]
hello, or maybe just use an operation queue to which all calls to Mixpanel instance are queued (except the initialization call of course) and is resumed when initialization is completed so they get executed after initialization.

**Comment by zihejia** [comment]
hi @AmrAbedal , sorry for the late response. Are you talking about the assertion that crashes the app? The intention of the assertion is to catch the issue early during the development phase and it won't crash in production. If you have a more specific use case, you are welcome to provide more information. Otherwise, I will close the issue for now.
