### ISSUE TITLE
Could not find module 'Mixpanel' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by rbpaul2** [mixpanel/mixpanel-swift#467]
When trying to build on simulator or preview SwiftUI components I get the following error:
```
Could not find module 'Mixpanel' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
```

I've tried including Mixpanel using both Swift Package Manager and CocoaPods. Have tried both version 2.10.2 and 3.0.0.beta with no luck.

I've tried setting Build Active Architecture Only to "No". Also added a User-defiend setting for VALID_ARCHS with "x86_64" listed.

Has anyone else run into this?

**Comment by rbpaul2** [comment]
I am using an M1 Macbook btw

**Comment by zihejia** [comment]
hi @rbpaul2 , if you are using SPM to integrate Mixpanel, then it is integrated as source code. It is up to you how to build it. Since you are using M1 Macbook, it is not x86_64. Could you try setting your `Architectures` to `Standard Architectures`?

**Comment by MobileMon** [comment]
I'm having this same issue. Any updates?

I'm building on an intel Macbook

**Comment by zihejia** [comment]
For anyone who has this issue, please set your `Architectures` to `Standard Architectures`, `Build Active Architecture Only`: Debug -> YES, Release -> NO. in your build settings. The reason is if you set Debug to NO, it will try to build the simulator build for all platforms but if you are on intel, you don't have the one for Arm, if you on M1, you don't have the one for x86. 

![image](https://user-images.githubusercontent.com/36679208/145116689-331e1eea-f80a-49a1-a1fe-632b702fd3d9.png)

Since this is not an issue related to the SDK itself, I'm closing this one now. Please feel free to reopen if you need further assistance.
