### ISSUE TITLE
Could not find module 'Mixpanel' for target 'arm64-apple-macos';

### ISSUE THREAD

**Issue by jen6** [mixpanel/mixpanel-swift#476]
In 3.0.0 beta there is no target for arm64 for macOS

**Comment by yousifa** [comment]
same problem here.. any updates?

**Comment by zihejia** [comment]
hi @jen6 or @yousifa  Do you have a screenshot for the error? If you are using SPM to integrate Mixpanel, then it is integrated as source code and our source code supports arm64.  It might be something to do with your build settings. What are your build settings for the below items? It may be worth clearing out your DerivedData folder and performing a complete rebuild.
![image](https://user-images.githubusercontent.com/36679208/134986856-9bf39862-065c-480d-ae64-8a8578c1f4cc.png)

**Comment by zihejia** [comment]
For anyone who has this issue, please set your `Architectures` to `Standard Architectures`, `Build Active Architecture Only`: Debug -> YES, Release -> NO. in your build settings. 

Since this is not an issue related to the SDK itself, I'm closing this one now. Please feel free to reopen if you need further assistance.
