### ISSUE TITLE
Stronger Type-safety and/or leniency for Properties

### ISSUE THREAD

**Issue by julien-c** [mixpanel/mixpanel-swift#5]
This one tripped me for a long while, because the crash it caused was only happening in production:

I was sending `launchOptions as? [String: AnyObject]` as `properties` in my app's `didFinishLaunchingWithOptions`, having read that `Properties` was just a typealias for `[String: AnyObject]`. 

For some possible values of `launchOptions` (say a `UIApplicationShortcutItem`), this is going to crash.

The library should either be more specific in its typing, or at least be lenient and not crash on unexpected input.

IMHO the number one goal of a library like this, is to never, ever trip the developers into unexpected crashes.

Thanks!

PS: would you say the library is production-ready yet? Have you heard of large-scale apps that have switched to it from the Obj-C one?

**Comment by julien-c** [comment]
(Another example re. my last remark: when calling `Mixpanel.mainInstance()` before calling `initialize()`, the lib shouldn't crash either. Better not to do anything rather than to crash. Just my 2 cents!)

**Comment by yarneo** [comment]
Hey @julien-c, we appreciate the input, and definitely understand your concern about crashing. 
To answer your first concern: launchOptions is actually defined in the SDK as [NSObject: AnyObject]? rather than Properties ([String: AnyObject]). Could that be the source of the crash? If not, please let me know where it is crashing and I would be happy to help you further with that.

To answer your second concern: You are 100% right about fixing that crash, we should be able to handle all behaviors and I will send out an update for that right away. Thank you for bringing this to our attention!!

In terms of if this lib is production-ready: It is only v1, and we are aware there could be things we might of missed, but we are pretty confident about the SDK, and we already have production apps using the SDK.

Let me know if you have any more questions! Have a great day!

**Comment by julien-c** [comment]
@yarneo On your first point: no, I was casting the SDK's launchOptions to a nullable `Properties?` using `if let ... as? [String: AnyObject]`.

Thanks for your help!
