### ISSUE TITLE
Inconsistent distinct_id handling with the mixpanel obj-c sdk

### ISSUE THREAD

**Issue by markhim** [mixpanel/mixpanel-swift#60]
It seems like here, you're trying to read the distinct_id from the unarchived properties - and in case they are not retrievable, you set it to "" (empty string) 
https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/Persistence.swift#L179
This seems like a good opportunity to set it to nil so that you can properly handle that issue somewhere

In your objc sdk on the other hand, you try to retrieve the distinct_id and then "generate" a new one (or use ifa/ifv if available) in case you couldn't read it from the archive.

Of course this is just a handling of an issue that should never occur anyway - but for us it did - the archive files were somehow corrupted and distinct_ids were reset - but at least they were just reset.
It looks like in this swift SDK, all users would end up getting an empty distinct_id --> all events would be attributed to the same "Mixpanel-user" with id ""

**Comment by yarneo** [comment]
Thank you for that! Your logic is sound, and yes as much as we don't expect a corrupt file, we should always fallback to the default behavior. I will push a change for this this week.

**Comment by markhim** [comment]
Awesome, thanks a lot for looking into this.

After diving deeper, I saw that you check if the distinct_id is empty string and then set it to the generated distinct_id here
https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/MixpanelInstance.swift#L615

So I guess the behavior ends up being the same as in the objective-c SDK overall.

Still I think the handling of corrupted archives could be done a bit more bulletproof - at least for the distinct_id. So maybe a combination of user-defaults for distinct_id and archives for properties might be an approach worth investigating

I know it's not trivial at all and supporting old iOS versions doesn't make it easier. I will also look into this and - in case I find an elegant solution - open a PR.

**Comment by yarneo** [comment]
Hey @markhim just wanted to follow up. It seems like you were right and we do set the empty distinctID to the default one if in fact the archive is corrupted. 

Do you think we should do any further steps in that matter? I'm guessing the best case scenario would be to save the distinctID in NSUserDefaults so that way we will try to fetch the distinctID from there if in fact we find that we lose it due to file corruption. 

Let me know if you think that would solve your problem or if you think the current handling is sound.

**Comment by markhim** [comment]
Hey @yarneo thanks for following up.

I also haven't come up with the master plan to create a robust `distinct_id`.
Afaik there are three options:

* UserDefaults: more robust, will be restored from backup, no way around it (changes meaning of distinct_id?)
* (Archive-/ or any other )File: can be corrupted "easier", can be restored from backup (changes meaning of distinct_id?) - however this can be prevented
* KeyChain: robust and secure, id remains in local keychain, even after reinstallation id stays (changes meaning of distinct_id?) - at least for now

I'm afraid all of them have advantages and disadvantages. And keeping in mind that for you and your customers it is probably incredibly important to keep the "meaning" of distinct_id consistent I don't think there is a simple solution.
If it's just about making the distinct_id more robust, then you could mirror it in UserDefaults and the old archive file. 
If the archive is corrupted the id is not lost. 
If Backup is restored (and the properties.archive was not restored -- see my following remark) you could generate a new id and mirror it again to userDefaults.
Doesn't really sound pretty though.

About the backup restore:
I realized that there might be another mismatch between your swift & objc lib:
In objc you call `addSkipBackupAttributeToItemAtPath` after writing any archive in order to set the `NSURLIsExcludedFromBackupKey` to `true`, causing the archive to not be restored from backup.

This looks intentional in objc, in swift however you don't do that, which changes the meaning of the `distinct_id` between the two SDKs.  Is this also true or am I missing sth here?

**Comment by yarneo** [comment]
Thanks for your elaborate reply @markhim !

I agree that all cases have advantages and disadvantages. In the case the file is indeed corrupted, we in both SDKs go and take the default distinct ID, which is usually an identifier for that specific device. It is true that if the user has been given a different distinctID by the developer, then it would be inconsistent and the user will now receive an unwanted distinctID.

I think that having userDefaults synchronized with the identify and alias settings could be helpful. However we do need to add that logic and test it thoroughly. I do intend to find time to work on this though for the next release.

In terms of `addSkipBackupAttributeToItemAtPath` we added it in the ObjC SDK because one user opened this issue https://github.com/mixpanel/mixpanel-iphone/issues/565 . I think it makes sense to add it to this SDK too so that will also be part of the same scope.

Thanks again for bringing this up and for conversing about the matter.

**Comment by yarneo** [comment]
Hey @markhim good news! I have added your suggestion in our latest PR and now the identity information is stored in UserDefaults and is fetched if the archive is corrupted. https://github.com/mixpanel/mixpanel-swift/pull/107
Will try to send out a release soon with this update included

**Comment by yarneo** [comment]
Released!
