### ISSUE TITLE
Support Privacy Manifest

### ISSUE THREAD

**Issue by RyotaIwai** [mixpanel/mixpanel-swift#620]
Please let me know when Privacy Manifest will be supported.
Apple has declared that this support will become required in the spring of 2024.

Thank you in advance.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by RyotaIwai** [comment]
Our application needs to be supported by May 1, 2024.
What is the timeline for Mixpanel’s Privacy Manifest support?

https://developer.apple.com/news/?id=3d8a9yyh

**Comment by xyn1nja** [comment]
Hey @RyotaIwai as I understand Mixpanel is actually not included in the [list of SDKs that require a privacy manifest](https://developer.apple.com/support/third-party-SDK-requirements/) so it's entirely optional and eng will not be prioritising it. If you really want to include it for your app, you can refer to this: https://mixpanel.com/legal/app-store-privacy-details/

**Comment by RyotaIwai** [comment]
@xyn1nja 

Hi.
I know Mixpanel is not on Apple's list.
But I understand that by May 1 our App needs to support Privacy Manifest.

For that we need to know about the API and data handling that Mixpanel is dealing with.
Is there no plan for Mixpanel to support Privacy Manifest at this time?

**Comment by nhelke** [comment]
@xyn1nja while I understand that Mixpanel is not singled out on Apple's list (yet), my reading of the [new requirements](https://developer.apple.com/news/?id=3d8a9yyh) vis-a-vis "need[ing] to declare approved reasons for using [[required reason APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)]" applies to app submissions as a whole, meaning that if Mixpanel uses any of those APIs and does not provide a privacy manifest, the app submission will be rejected.

I guess we will find out on March 13 if we start getting warnings when submitting.

**Comment by benMohamed** [comment]
You need to update your code to support Apple's privacy requirements; otherwise, we will be forced to change your SDK :(

**Comment by benMohamed** [comment]
Me too I got this message because of Mixpanel sdk
`
 
--
 
Hello,We noticed one or more issues with a recent submission for App Store review for the following app Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.ITMS-91053: Missing API declaration - Your app’s code in the “App” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.ITMS-91053: Missing API declaration - Your app’s code in the “App” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.ITMS-91053: Missing API declaration - Your app’s code in the “App” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

`

**Comment by jaredmixpanel** [comment]
`v4.2.1` has been released with a privacy manifest that declares the use of the `UserDefaults` API

**Comment by mahavrani** [comment]
Please let us know in mixpanel cocoapods from which version Privacy manifest support is available ? Current version is 5.0.2 doesnt have the support.
https://cocoapods.org/pods/Mixpanel

**Comment by jaredmixpanel** [comment]
`v4.2.2` has just been released to move the privacy manifest to the correct location in the project. In `v4.2.1` it was incorrectly located under the sample app in the repo, not the actual SDK, sorry about that.
