### ISSUE TITLE
App Release ($app_release) and version ($app_version) not populated

### ISSUE THREAD

**Issue by appsforall** [mixpanel/mixpanel-swift#63]
We migrated from the objc library to this MixpanelSwift library as our project is moving to swift. With the 'old' mixpanel library, the $app_release and $app_version were populated automatically on each event (as documented here: https://mixpanel.com/help/questions/articles/what-properties-do-mixpanels-libraries-store-by-default

However, in this MixPanel-Swift library, they do not get populated anymore. They now always have the value 'undefined'.

**Comment by appsforall** [comment]
I created a PR with a solution for above issue. Hope you are willing to consider it. https://github.com/mixpanel/mixpanel-swift/pull/64

**Comment by yarneo** [comment]
Thanks for spotting that and creating a PR. The actual reason we didn't add those 2 properties ($app_release, $app_version) to the Swift SDK is because they are properties we are in the process of deprecating. Instead, we have two newer properties called $app_build_number and $app_version_string. They present the exact same data as the older properties and show up in your properties dropdown as their original names. We will in the future eventually map them to "App Version" and "App Release" but in the meanwhile they will just show as their original names.

Let me know if that makes sense! For now, I recommend using $app_build_number and $app_version_string in your Mixpanel report to look at your app's version and build number!

Thanks!

**Comment by yarneo** [comment]
Also thanks for letting us know that our help guide documentation is mentioning the deprecated fields, I have opened a request to update that so it's more upto date!

**Comment by appsforall** [comment]
Hi Yarden,

Thanks for your extensive reply. I fully agree: If you are going to deprecate them there is no use in adding the fields.
I will inform our product manager that he should use the new fields to filter.

Regards,
Wim

**Comment by yarneo** [comment]
Good news! We have updated the doc to show the correct internal properties we use for "App Build Number" and "App Version". Hope it is clearer now :) (Sorry it took so long)

**Comment by sandrop8** [comment]
You guys should really do a "news announcement" within mixpanel dashboard. People who use you for a long time (and always breakdown important funnels by versions) are not looking at the docs to see if something is deprecated. I was wondering what I did wrong in my code all the time and did not even thought about to research if other have this problem on stackoverflow.

Nevertheless now everything is fine with the new properties 🙏

**Comment by hadiche** [comment]
+1
We were caught by surprise when 'App Version' started to post undefined values.
