### ISSUE TITLE
Drop DECIDE flag

### ISSUE THREAD

**Issue by arthur-here** [mixpanel/mixpanel-swift#95]
Hi guys. First of all, thanks for the open-sourced official library 🙂
I have a question regarding `DECIDE` flag. It's impossible to disable codeless tracking with Carthage now. Is there any reason why we use compiler flag instead of a property?
Thanks

**Comment by yarneo** [comment]
Hey, thanks for writing in. Is there a reason why you would want to disable codeless tracking on your main app? What you could do is disable the connection to the visual editor for codeless by setting `enableVisualEditorForCodeless` to false.

**Comment by arthur-here** [comment]
Thanks for the response @yarneo. I've spent some time profiling my app with Time Profiler and looks like codeless tracking slows down UI a lot. For example

**Comment by arthur-here** [comment]
Thanks for the response @yarneo. I've spent some time profiling my app with Time Profiler and looks like codeless tracking slows down UI a lot. For example, during new view controller presentation swizzled code in `newDidMoveToWindow` takes up to 75% of weight in time profiler which causes UI delays. 
`enableVisualEditorForCodeless` doesn't fix the problem, but the binary built without DECIDE flag does
It would be awesome to have a possibility to disable codeless tracking with some property, or by argument in the `Mixpanel.initialize` 🤓

**Comment by yarneo** [comment]
Thanks for the info! I understand your concern and it is possible we will do something like that in the future. What I do suggest in the meanwhile (if you don't want to integrate with CocoaPods or manually) is to just remove all the codeless events from within the Mixpanel UI. By removing them and disabling the visual editor with `enableVisualEditorForCodeless` you are making sure no swizzling will or can occur.

**Comment by arthur-here** [comment]
That is great, thanks!

**Comment by yarneo** [comment]
Hey @arthur-here just a small update. I've tried to see if a property would be an east add. I initially tried to add it in a way that it isn't an added property to `initialize` because that would make the `initialize` more complicated for people who for instance just want to add a custom `flushInterval` or `instanceName`. I could add another `initialize` method with that flag but it seems like a bit of an overkill. Then I looked at trying to add it as a property you can set. The problem with that is that during the initialization of the Mixpanel instance we already execute cached a/b tests and codeless events. Therefore if it is set after the initialization it would be too late. I'm hoping the current solution works well for you and if not feel free to reopen this issue and we can discuss this further and find a good solution. Thanks!

**Comment by jcavar** [comment]
We would also like to do this. We only really need manual tracking and all dynamic swizzling stuff seems a bit scary so we would like to get rid of it. 
Would it be possible to provide subspec for this to integrate withouth `DECIDE` (and without files required by DECIDE I guess)?

**Comment by ThoseGuysInTown** [comment]
**Removing all codeless tracking events** and setting `enableVisualEditorForCodeless` to false worked for me! Thanks @arthur-here and @yarneo for posting and resolving this issue, the UI issues had been keeping me up at night! 😆
